packages:
  - packages/*

catalog:
  '@inquirer/checkbox': ^4.2.4
  '@inquirer/confirm': ^5.1.16
  '@inquirer/editor': ^4.2.18
  '@inquirer/input': ^4.2.2
  '@inquirer/number': ^3.0.18
  '@inquirer/password': ^4.0.18
  '@inquirer/select': ^4.3.2
  minimist: ^1.2.8

onlyBuiltDependencies:
  - '@biomejs/biome'
