packages:
  - packages/*

catalog:
  '@inquirer/checkbox': ^4.1.8
  '@inquirer/confirm': ^5.1.12
  '@inquirer/editor': ^4.2.13
  '@inquirer/input': ^4.2.2
  '@inquirer/number': ^3.0.15
  '@inquirer/password': ^4.0.15
  '@inquirer/select': ^4.2.3
  minimist: ^1.2.8

onlyBuiltDependencies:
  - '@biomejs/biome'
