packages:
  - packages/*

settings:
  catalogMode: strict
  cleanupUnusedCatalogs: true

catalog:
  '@inquirer/checkbox': ^5.1.2
  '@inquirer/confirm': ^6.0.10
  '@inquirer/editor': ^5.0.10
  '@inquirer/input': ^5.0.10
  '@inquirer/number': ^4.0.10
  '@inquirer/password': ^5.0.10
  '@inquirer/select': ^5.1.2
  minimist: ^1.2.8

onlyBuiltDependencies:
  - '@biomejs/biome'
